### ISSUE TITLE
better instructions for installing GSL

### ISSUE THREAD

**Issue by waynelapierre** [RfastOfficial/Rfast#41]
**Is your feature request related to a problem? Please describe.**
When I installed Rfast on Fedora, the error message said GSL is missing. For most other R packages I worked with, typically they will show detailed platform-specific instructions on how to install the missing packages.  

**Describe the solution you'd like**
Just add something like:
for fedora: sudo dnf install gsl-devel
for debian: blabla..
etc.

**Comment by ManosPapadakis95** [comment]
To be honest as I remember in Rfast we don't use GSL immediately. Rcpp is responsible for this. I mean the GSL is used for the mathematical operations by Rcpp and RcppArmadillo (I think). So maybe you should search in their sites if you are missing something from the Rcpp side. 
I had a similar problem once but it was Rcpp. After some research I found that R didn't install correctly the gsl because I was missing a command. Something like that. That happened 4 years ago.
Even if you have install gsl and R can't find the libraries check if your path is set correctly.

**Comment by waynelapierre** [comment]
You are right. The issue is from the package RcppGSL.
