### ISSUE TITLE
matrnorm return errors

### ISSUE THREAD

**Issue by xiekunwhy** [RfastOfficial/Rfast#49]
Hi,

I got the following errors when using matrnorm, do you know why?

> library(Rfast)
Loading required package: Rcpp
Loading required package: RcppZiggurat
> x <- matrnorm(37488, 130123)
Error in RcppZiggurat::zrnorm(n * p) : 
  negative length vectors are not allowed
In addition: Warning message:
In RcppZiggurat::zrnorm(n * p) :
  NAs introduced by coercion to integer range

Best,
Kun

**Comment by StefanosFafalios** [comment]
Hello xiekunwhy,

Thank you for notifying us. 
As you can observe, the error actually comes from package RcppZiggurat::zrnorm. 
This most probably happens because 37488 * 130123 = 4878051024, whereas INTEGER_MAX_VALUE = 2147483647.
This issue could be resolved if the RcppZiggurat developers set zrnorm accept long as input instead of int. 
For now RcppZiggurat can not handle such matrix sizes. Try reducing the number of rows (n) or number of columns (p) 
so that n * p < 2147483647

Best,
Rfast team

P.S. this issue will be closed since it is occuring in another package.
