### ISSUE TITLE
imbalanced class labels in knn?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [RfastOfficial/Rfast#55]
**Is your feature request related to a problem? Please describe.**

Regarding knn, when class labels are imbalanced, it may need some
mitigation, such as weighting neighbors by the inverse of their class
size. But I don't see options of Rfast's knn() for imbalance class
problems.

https://stats.stackexchange.com/questions/341/knn-and-unbalanced-classes

How to address the imbalance problem with Rfast's knn()?

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
NA.

**Additional context**
NA.

**Comment by statlink** [comment]
Hello,

We do not do that because I had seen in some examples it did not improve the predictive accuracy. You might be right. I think we have this option in the dirknn() function, yet, it is not exported in R. Would you be interested in this? The difference is that the data are first normalised to have unit norm. Each vector is normalised, not each feature. We could export it in R. 
Please let me know.

Michail
